Home page
Pranjal-R-Agrawal/CSC207_Course_Project_141 pull request #25
Opened 2023-11-29 03:01 UTC by Tanmay-Shinde

2023-11-29 03:24 UTC, Pranjal-R-Agrawal commented
Since the homepage view has been implemented now, you should modify the login use case so that the loginpresenter switches to the homepage after a successfull login. Then add a test to `MainViewTest.java` to check if a successful login opens the `HomePageView`.

You can do so by 
1. Modifying `LoginUseCaseFactory.create()` to accept the `HomePageViewModel`, 
2. Modifying `LoginUseCaseFactory.createUserLoginUseCase()` to accept the `HomePageViewModel`,
3. Modifying `LoginPresenter`'s contructor to accept `HomePageViewModel`,
4. Modifying `LoginPresenter.prepareSuccessView()` to call `viewManagerModel.setActiveView(HomePageViewModel.getViewName()); viewManagerModel.firePropertyChanged();`

2023-11-29 03:31 UTC, Pranjal-R-Agrawal commented on src/main/java/view/HomePageView.java
> +        this.viewProfileViewModel = viewProfileViewModel;
Also, we will have to wait before we can merge this into main because your code references `GenerateIdeaViewModel`, `CreatePostViewModel` and `ViewProfileViewModel`, neither of which exist yet, at least in this branch and main, thus resulting in errors. And we cannot have code with errors in main.

Ig you could create placeholder files for now and add TODOs.

2023-12-04 21:26 UTC, SidharthSawhney requested changes
Please make the required changes according to what Pranjal and I have described. Thank you!

2023-12-05 00:07 UTC, Tanmay-Shinde commented on src/main/java/view/HomePageViewModel.java
> +        support.firePropertyChange(propertyName, null, "view");
The ViewModel for Home Page does not have a state attribute as there is no corresponding HomePageState class. This is because the home page is not really a proper use case. 

And in my opinion, adding a state class for the home page will be unnecessary as the home page only ever has one state and it is always the same as there are no dynamic elements.

2023-12-05 05:00 UTC, Tanmay-Shinde reviewed
Added Javadoc in all the files

2023-12-05 22:48 UTC, Pranjal-R-Agrawal commented
@Tanmay-Shinde follow the steps in my previous review to integrate the home page and login use case.

2023-12-05 23:50 UTC, Tanmay-Shinde commented
Implemented functionality to integrate home page and login use case. All action items done except testing (will do it soon). 

We might still have to wait for the view_profile_use_case branch to be merged into main before merging this branch.

2023-12-06 06:40 UTC, SidharthSawhney requested changes
Java doc is required in some places as indicated

2023-12-06 06:40 UTC, SidharthSawhney commented on src/main/java/app/LoginUseCaseFactory.java
>  public class LoginUseCaseFactory {
Javadoc the the class and public methods required here

2023-12-06 06:40 UTC, SidharthSawhney commented on src/main/java/use_case/login/interface_adapter/LoginPresenter.java
>  public class LoginPresenter implements LoginOutputBoundary {
Java doc required for here for class and public methods

2023-12-07 04:05 UTC, Pranjal-R-Agrawal approved these changes
Excellent work with the home page and integrating it with the login view.

2023-12-07 04:15 UTC, SidharthSawhney approved these changes
Well done!

2023-12-07 04:33 UTC, merged