Login signup fixes
Pranjal-R-Agrawal/CSC207_Course_Project_141 pull request #32
Opened 2023-12-04 06:38 UTC by Pranjal-R-Agrawal

1. Resolved #3
2. Resolved #6
3. Resolved #13
4. Added isolated interactor tests
5. Added JavaDoc

2023-12-04 21:25 UTC, SidharthSawhney requested changes
JavaDoc for all public classes and public constructors and methods are required, there are some place that hasn't been included. Clean Architecture is being followed well as the dependencies are pointing inwards. Please check the inline reviews for specific changes that are required. Well done!

2023-12-04 21:25 UTC, SidharthSawhney commented on src/test/java/use_case/signup/SignupInteractorTest.java
> +            mongoDBDataAccessObject = new MongoDBDataAccessObjectBuilder().setTestParameters().build();
Just like the Login Interactor test modification that is required, we need to do the same thing here as well.

2023-12-04 21:25 UTC, SidharthSawhney commented on src/test/java/use_case/display_post/DisplayPostInteractorTest.java
> +            mongoDBDataAccessObject = new MongoDBDataAccessObjectBuilder().setTestParameters().build();
Same recommendation in LoginInteractor applies here too.

2023-12-04 21:25 UTC, SidharthSawhney commented on src/test/java/use_case/login/LoginInteractorTest.java
> +            public void prepareFailView(String error) {fail();}
A message in fail() would be a nice addition and everywhere where fail() is used-maybe state the reason of failure

2023-12-04 21:25 UTC, SidharthSawhney commented on src/main/java/use_case/signup/interface_adapter/SignupPresenter.java
>          viewManagerModel.firePropertyChanged();
this code could be replaced by having  goToLogin() invoked here

2023-12-04 21:25 UTC, SidharthSawhney commented on src/test/java/use_case/signup/SignupInteractorTest.java
> +        mongoDBDataAccessObject.addUser(new User("username", "password", "name", "email", "phone", "city", "field"));
User factory should be used to create user preferably, to abide with the Single Responsibility Principle

2023-12-04 21:25 UTC, SidharthSawhney commented on src/main/java/app/DisplayPostUseCaseFactory.java
>  public class DisplayPostUseCaseFactory {
Factory Design pattern well implemented

2023-12-04 21:25 UTC, SidharthSawhney commented on src/main/java/view/SignupView.java
>      public SignupView(SignupViewModel signupViewModel, SignupController signupController) {
Add Javadoc

2023-12-06 00:11 UTC, Pranjal-R-Agrawal commented on src/test/java/use_case/login/LoginInteractorTest.java
> +            public void prepareFailView(String error) {fail();}
There isn't any particular reason, just that the the input is valid so the interactor shouldn't fail.

2023-12-06 00:13 UTC, Pranjal-R-Agrawal commented
@SidharthSawhney I have made the requested changes.

2023-12-06 05:57 UTC, SidharthSawhney requested changes
Interactor tests are well implemented! Integration tests are now required to be done where we use the real MongoDB database instead of the mock, take a look at the current main, ull see how each use case has an integration test and interactor. Ur previous code for the tests with the real DB was correct but I said back then to keep those and rename them to integration tests instead of interactor tests. This will help with line coverage, moreover tests for interactor integration and interactor with mock DB is a requirement for us! Overall, well done!

2023-12-06 05:57 UTC, SidharthSawhney commented on src/test/java/use_case/display_post/DisplayPostInteractorTest.java
> +    MockSignupLoginDisplayPostDataAccessObject mongoDBDataAccessObject;
you will  have to change the file variable names as it could get confusing in all the interactor tests

2023-12-06 05:57 UTC, SidharthSawhney commented on src/main/java/view/SignupView.java
> +    /**
The SignupView class on line 13 will also need javadoc

2023-12-06 06:02 UTC, Pranjal-R-Agrawal commented
> Integration tests are now required to be done where we use the real MongoDB database instead of the mock

Aren't integration tests beyond the scope for the project? I believe the DAO tests (implemented in another branch, merged into main by now), combined with the isolated interactor tests should be enough.

2023-12-06 06:57 UTC, SidharthSawhney approved these changes

2023-12-06 07:06 UTC, YathusanK approved these changes
Fixes to code function well and JavaDoc was added to public methods. Your interactor and integration tests also are written well!

2023-12-06 07:06 UTC, merged