View Profile Use Case
Pranjal-R-Agrawal/CSC207_Course_Project_141 pull request #33
Opened 2023-12-04 23:09 UTC by anbu1504

1. Implemented the view profile use case
2. Displays username, name, email, and rating
3. Has logout and back button
4. Tests are implemented

2023-12-05 06:16 UTC, YathusanK commented
According to our UI flow, the view profile screen should also show the projects of the user as well as collaboration requests.

2023-12-05 14:55 UTC, YathusanK requested changes

2023-12-05 20:56 UTC, YathusanK commented on src/main/java/data_access/ViewProfileDataFileAccessObject.java
This file is actually used for testing the interactor in isolation from the actual database.

2023-12-06 09:08 UTC, Pranjal-R-Agrawal commented on src/main/java/view/ViewProfileView.java
> +        addComponent(ratingsPanel, c, 0, GridBagConstraints.RELATIVE, GridBagConstraints.HORIZONTAL);
We aren't implementing the rating system anymore, so this should be removed / commented out

2023-12-07 04:36 UTC, Tanmay-Shinde approved these changes
Great work, all commits look good. ready to merge.

2023-12-07 04:39 UTC, YathusanK approved these changes
Good work! Your changes fixed the earlier mentioned issues. Your code also adheres Clean Architecture and it functions correctly.

2023-12-07 05:40 UTC, merged